on:
  release:
    types: [ created ]

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.42
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          goos: linux
          goarch: amd64
          extra_files: gitcd-go-runner.sh
