on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  pull-requests: read

jobs:
  release-on-tag-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor